--------------------------------------------------------
-- Archivo creado  - jueves-octubre-22-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_SIS_CODIGO_PUESTO
--------------------------------------------------------

   CREATE SEQUENCE  "SIGAMM"."SEQ_SIS_CODIGO_PUESTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SIS_CODIGO_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "SIGAMM"."SEQ_SIS_CODIGO_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table SIS_GIRO_COMERCIAL
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" 
   (	"CODIGO_GIRO" NUMBER, 
	"NOMBRE_GIRO" VARCHAR2(200 BYTE), 
	"SECTOR" VARCHAR2(2 BYTE), 
	"ESTADO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_MENU
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_MENU" 
   (	"CODIGO_MENU" NUMBER, 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ORDEN" NUMBER, 
	"ESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_MENU_NIVELES
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_MENU_NIVELES" 
   (	"CODIGO_NIVELES" NUMBER, 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"LINK" VARCHAR2(200 BYTE), 
	"ORDEN" NUMBER, 
	"NIVEL" NUMBER, 
	"ESTADO" NUMBER(1,0), 
	"CODIGO_MENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_MENU_USUARIO
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_MENU_USUARIO" 
   (	"CODIGO_MENU_USUARIO" NUMBER, 
	"CODIGO_NIVELES" NUMBER, 
	"CODIGO_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_PUESTO
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_PUESTO" 
   (	"CODIGO_PUESTO" NUMBER, 
	"CODIGO_USUARIO" NUMBER, 
	"NRO_PUESTO" VARCHAR2(4 BYTE), 
	"CODIGO_GIRO" NUMBER, 
	"USUARIO_REGISTRO" VARCHAR2(20 BYTE), 
	"FECHA_REGISTRO" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"ESTADO" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_ROL
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_ROL" 
   (	"CODIGO_ROL" NUMBER, 
	"NOMBRE_ROL" VARCHAR2(200 BYTE), 
	"ESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_ROL_X_UNIDAD
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" 
   (	"CODIGO_ROL_X_UNIDAD" NUMBER, 
	"CODIGO_UNIDAD" NUMBER, 
	"CODIGO_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_UNIDAD
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_UNIDAD" 
   (	"CODIGO_UNIDAD" NUMBER, 
	"NOMBRE_UNIDAD" VARCHAR2(200 BYTE), 
	"ESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIS_USUARIO
--------------------------------------------------------

  CREATE TABLE "SIGAMM"."SIS_USUARIO" 
   (	"CODIGO_USUARIO" NUMBER, 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CLAVE" VARCHAR2(40 BYTE), 
	"DNI" VARCHAR2(8 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(30 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(30 BYTE), 
	"NOMBRES" VARCHAR2(40 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"CORREO" VARCHAR2(200 BYTE), 
	"ESTADO" NUMBER(1,0), 
	"USUARIO_CREACION" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"CODIGO_ROL_X_UNIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIGAMM.APEX$_ACL
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_FILES
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_HISTORY
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_LINKS
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_NOTES
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_ROWS
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_TAGS
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_WEBPG_SECTION_HISTORY
SET DEFINE OFF;
REM INSERTING into SIGAMM.APEX$_WS_WEBPG_SECTIONS
SET DEFINE OFF;
REM INSERTING into SIGAMM.SIS_GIRO_COMERCIAL
SET DEFINE OFF;

Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('3','BAZAR-COSMETOLOGIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('4','BAZAR-JOYERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('5','BAZAR-JUGUETERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('6','BAZAR-LENCERÍA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('7','BAZAR-LIBRERÍA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('8','BAZAR-LOCERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('9','BAZAR-PASAMANERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('10','BAZAR-RELOJERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('1','BAZAR','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('2','BAZAR-ARTESANÍA-SOMBRERO','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('11','BAZAR-ZAPATERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('12','JUGUETERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('13','LICORERIA-CONFITERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('14','LOCERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('15','LOCERIA-PLASTICOS','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('16','LOCERIA-PLASTICOS-JUGUET.','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('17','PLASTICOS','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('18','RELOJERÍA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('19','RELOJERÍA-JOYERÍA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('20','ZAPATERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('21','ZAPATERIA-PASAMANERIA','01','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('22','GOLOSINAS','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('23','GOLOSINAS-PERIODICO-REVIST.','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('24','GOLOSINAS-PIÑATERIA','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('25','IMPRENTA','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('26','IMPRENTA-LIBRERÍA','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('27','LIBRERÍA','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('28','LIBRERÍA-REVISTAS','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('29','PERIODICO-REVISTAS','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('30','PIÑATERIA','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('31','PIÑATERIA-DESCARTABLES','02','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('32','CONFECCION DE ROPA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('33','CONFECCION Y VENTA- ROPA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('34','FRAZADAS-CUBRECAMAS','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('35','MERCERIA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('36','MERCERIA-DESCARTABLES','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('37','MERCERIA-SOMBRERO','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('38','ROPA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('39','ROPA DE NIÑOS','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('40','ROPA-FRAZADAS','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('41','ROPA-LENCERÍA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('42','ROPA-MERCERIA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('43','ROPA-SOMBREROS','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('44','ROPA-TELA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('45','SOMBREROS','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('46','TELA','03','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('47','ABARROTES','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('48','ABARROTES-ALIM. BALANCEAD.','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('49','ABARROTES-GRANOS SECOS','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('50','ALIMENTOS BALANCEADOS','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('51','ARTICULOS DE LIMPIEZA','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('52','BODEGA','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('53','GRANOS SECOS','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('54','GRANOS Y FRUTAS SECAS','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('55','NATURISTA','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('56','NATURISTA','04','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('57','CEVICHERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('58','COMIDA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('59','COMIDA-CEVICHERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('60','COMIDA-CEVICHERIA-CAFETERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('61','DULCERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('62','EMBUTIDOS','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('63','EMBUTIDOS Y LACTEOS','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('64','EMOLIENTES','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('65','FUENTE DE SODA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('66','JUGUERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('67','JUGUERIA-COMIDA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('68','JUGUERIA-DULCERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('69','JUGUERIA-DULCERIA-REFRESCO','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('70','JUGUERIA-EMOLIENTES','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('71','JUGUERIA-REFRESCO','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('72','PANADERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('73','PANADERIA-EMBUTIDOS','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('74','PANADERIA-LACTEOS','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('75','PANADERIA-PASTELER.-EMBUTID.','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('76','PANADERIA-PASTELERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('77','PASTELERIA','05','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('78','ANTIGÜEDADES-ARTESANIAS','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('79','ARTESANIA','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('80','CARBÓN','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('81','DECORACION','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('82','ELECTRODOMESTICOS','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('83','ELECTRODOM-FERRETERIA','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('84','FERRETERIA      ','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('85','FLORERIA','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('86','MUEBLERIA','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('87','REPUESTOS','06','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('88','ALFALFA','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('89','FRUTAS','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('90','FRUTAS-PLANTAS FRUTALES','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('91','LIMONES','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('92','TUBERCULOS','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('93','VERDURA CHINA','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('94','VERDURAS','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('95','VERDURAS-CHOCLOS','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('96','VERDURAS-GRANOS VERDES','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('97','VERDURAS-LIMONES','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('98','VERDURAS-TUBERCULOS','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('99','VERDURAS-TUBERCULOS-LIMONES','07','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('100','CASSETTES','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('101','CASSETTES-CD','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('102','CASSETTES-CD-VIDEOS','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('103','EQUIPO-SIST.COMP-CASSET','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('104','PELUQUERIA-SALON BELLEZA','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('105','PRODUCTOS VETERINARIOS','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('106','RENOVADORA CALZADO','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('107','SALON DE BELLEZA','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('108','TECNICO ELECTRONICA','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('109','AVES','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('110','AVES-HUEVOS','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('111','AVES-MENUDENCIAS','08','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('112','CARNE','09','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('113','CARNE-AVES-MENUDENCIAS','09','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('114','CARNE-MENUDENCIA','09','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('115','MENUDENCIAS','09','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('116','MARISCOS','10','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('117','PESCADOS Y MARISCOS','10','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('118','ESPECERIA','11','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('119','ESPECERIA-DESCARTABLE','11','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('120','ESPECIES-BOLSAS PLÁSTICAS','11','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('121','ESPECIES-DETERGENTES','11','1');
Insert into SIGAMM.SIS_GIRO_COMERCIAL (CODIGO_GIRO,NOMBRE_GIRO,SECTOR,ESTADO) values ('122','ANIMALES VIVOS','12','1');
REM INSERTING into SIGAMM.SIS_MENU
SET DEFINE OFF;
Insert into SIGAMM.SIS_MENU (CODIGO_MENU,DESCRIPCION,ORDEN,ESTADO) values ('1','Reportes','1','1');
Insert into SIGAMM.SIS_MENU (CODIGO_MENU,DESCRIPCION,ORDEN,ESTADO) values ('2','Mantenimiento','2','1');
Insert into SIGAMM.SIS_MENU (CODIGO_MENU,DESCRIPCION,ORDEN,ESTADO) values ('3','Seguridad','3','1');
REM INSERTING into SIGAMM.SIS_MENU_NIVELES
SET DEFINE OFF;
Insert into SIGAMM.SIS_MENU_NIVELES (CODIGO_NIVELES,DESCRIPCION,LINK,ORDEN,NIVEL,ESTADO,CODIGO_MENU) values ('1','Usuario','usuarios','1','1','1','2');
Insert into SIGAMM.SIS_MENU_NIVELES (CODIGO_NIVELES,DESCRIPCION,LINK,ORDEN,NIVEL,ESTADO,CODIGO_MENU) values ('2','Puesto','puesto','2','1','1','2');
REM INSERTING into SIGAMM.SIS_MENU_USUARIO
SET DEFINE OFF;
Insert into SIGAMM.SIS_MENU_USUARIO (CODIGO_MENU_USUARIO,CODIGO_NIVELES,CODIGO_USUARIO) values ('1','1','1');
Insert into SIGAMM.SIS_MENU_USUARIO (CODIGO_MENU_USUARIO,CODIGO_NIVELES,CODIGO_USUARIO) values ('2','2','1');
REM INSERTING into SIGAMM.SIS_PUESTO
SET DEFINE OFF;
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('2','1','0145','47','1',to_date('22/10/15','DD/MM/RR'),'1',to_date('22/10/15','DD/MM/RR'),'0');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('3','1','1855','67','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('4','1','1874','109','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('5','1','4787','13','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('6','1','4787','13','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('7','1','4787','13','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('8','1','1234','122','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('10','1','2010','47','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('9','1','2015','47','1',to_date('22/10/15','DD/MM/RR'),'1',to_date('22/10/15','DD/MM/RR'),'1');
Insert into SIGAMM.SIS_PUESTO (CODIGO_PUESTO,CODIGO_USUARIO,NRO_PUESTO,CODIGO_GIRO,USUARIO_REGISTRO,FECHA_REGISTRO,USUARIO_MODIFICACION,FECHA_MODIFICACION,ESTADO) values ('11','2','2020','103','1',to_date('22/10/15','DD/MM/RR'),null,null,'1');
REM INSERTING into SIGAMM.SIS_ROL
SET DEFINE OFF;
Insert into SIGAMM.SIS_ROL (CODIGO_ROL,NOMBRE_ROL,ESTADO) values ('1','CAJERO','1');
REM INSERTING into SIGAMM.SIS_ROL_X_UNIDAD
SET DEFINE OFF;
Insert into SIGAMM.SIS_ROL_X_UNIDAD (CODIGO_ROL_X_UNIDAD,CODIGO_UNIDAD,CODIGO_ROL) values ('1','1','1');
REM INSERTING into SIGAMM.SIS_UNIDAD
SET DEFINE OFF;
Insert into SIGAMM.SIS_UNIDAD (CODIGO_UNIDAD,NOMBRE_UNIDAD,ESTADO) values ('1','TESORERIA','1');
REM INSERTING into SIGAMM.SIS_USUARIO
SET DEFINE OFF;
Insert into SIGAMM.SIS_USUARIO (CODIGO_USUARIO,USUARIO,CLAVE,DNI,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,FECHA_NACIMIENTO,CORREO,ESTADO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION,TELEFONO,CODIGO_ROL_X_UNIDAD) values ('1','JAMBROCIO','xwfdLpX9xWGyYWnHQK2CRQ==','42596272','AMBROCIO','SERNAQUE','JORGE CHRISTIAN',to_date('30/08/84','DD/MM/RR'),'JAMBROCIO@PENSION65.GOB.PE','1','JAMBROCIO',to_date('20/10/15','DD/MM/RR'),'JAMBROCIO',null,'951294596','1');
Insert into SIGAMM.SIS_USUARIO (CODIGO_USUARIO,USUARIO,CLAVE,DNI,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,FECHA_NACIMIENTO,CORREO,ESTADO,USUARIO_CREACION,FECHA_CREACION,USUARIO_MODIFICACION,FECHA_MODIFICACION,TELEFONO,CODIGO_ROL_X_UNIDAD) values ('2','JMUNOZ','1sNqrIyO5b0=','42596277','MUNOZ','CAVERO','JOHAN ARTEMIO',to_date('20/10/15','DD/MM/RR'),'JMUNOZC@PENSION65.GOB.PE','1','JAMBROCIO',to_date('20/10/15','DD/MM/RR'),'JAMBROCIO',null,'324345345','1');
--------------------------------------------------------
--  DDL for Index SIS_MENU_NIVELES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_MENU_NIVELES_PK" ON "SIGAMM"."SIS_MENU_NIVELES" ("CODIGO_NIVELES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_MENU_PK" ON "SIGAMM"."SIS_MENU" ("CODIGO_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_UNIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_UNIDAD_PK" ON "SIGAMM"."SIS_UNIDAD" ("CODIGO_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_ROL_X_UNIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_ROL_X_UNIDAD_PK" ON "SIGAMM"."SIS_ROL_X_UNIDAD" ("CODIGO_ROL_X_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_MENU_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_MENU_USUARIO_PK" ON "SIGAMM"."SIS_MENU_USUARIO" ("CODIGO_MENU_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_USUARIO_PK" ON "SIGAMM"."SIS_USUARIO" ("CODIGO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_PUESTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_PUESTO_PK" ON "SIGAMM"."SIS_PUESTO" ("CODIGO_PUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_ROL_PK" ON "SIGAMM"."SIS_ROL" ("CODIGO_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SIS_GIRO_COMERCIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGAMM"."SIS_GIRO_COMERCIAL_PK" ON "SIGAMM"."SIS_GIRO_COMERCIAL" ("CODIGO_GIRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SIS_MENU
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_MENU" ADD CONSTRAINT "SIS_MENU_PK" PRIMARY KEY ("CODIGO_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_MENU" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU" MODIFY ("ORDEN" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU" MODIFY ("CODIGO_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_ROL
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_ROL" ADD CONSTRAINT "SIS_ROL_PK" PRIMARY KEY ("CODIGO_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_ROL" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_ROL" MODIFY ("NOMBRE_ROL" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_ROL" MODIFY ("CODIGO_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_PUESTO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("USUARIO_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("CODIGO_GIRO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_PUESTO" ADD CONSTRAINT "SIS_PUESTO_PK" PRIMARY KEY ("CODIGO_PUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("NRO_PUESTO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_PUESTO" MODIFY ("CODIGO_PUESTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_GIRO_COMERCIAL
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" ADD CONSTRAINT "SIS_GIRO_COMERCIAL_PK" PRIMARY KEY ("CODIGO_GIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" MODIFY ("SECTOR" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" MODIFY ("NOMBRE_GIRO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_GIRO_COMERCIAL" MODIFY ("CODIGO_GIRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_USUARIO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_USUARIO" ADD CONSTRAINT "SIS_USUARIO_PK" PRIMARY KEY ("CODIGO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("CODIGO_ROL_X_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("USUARIO_CREACION" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("APELLIDO_PATERNO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_USUARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_UNIDAD
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_UNIDAD" ADD CONSTRAINT "SIS_UNIDAD_PK" PRIMARY KEY ("CODIGO_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_UNIDAD" MODIFY ("CODIGO_UNIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_MENU_NIVELES
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" ADD CONSTRAINT "SIS_MENU_NIVELES_PK" PRIMARY KEY ("CODIGO_NIVELES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("NIVEL" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("ORDEN" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("LINK" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" MODIFY ("CODIGO_NIVELES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_MENU_USUARIO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" MODIFY ("CODIGO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" MODIFY ("CODIGO_NIVELES" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" ADD CONSTRAINT "SIS_MENU_USUARIO_PK" PRIMARY KEY ("CODIGO_MENU_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" MODIFY ("CODIGO_MENU_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIS_ROL_X_UNIDAD
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" ADD CONSTRAINT "SIS_ROL_X_UNIDAD_PK" PRIMARY KEY ("CODIGO_ROL_X_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" MODIFY ("CODIGO_ROL" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" MODIFY ("CODIGO_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" MODIFY ("CODIGO_ROL_X_UNIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SIS_MENU_NIVELES
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_MENU_NIVELES" ADD CONSTRAINT "SIS_MENU_NIVELES_FK1" FOREIGN KEY ("CODIGO_MENU")
	  REFERENCES "SIGAMM"."SIS_MENU" ("CODIGO_MENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIS_MENU_USUARIO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" ADD CONSTRAINT "SIS_MENU_USUARIO_FK1" FOREIGN KEY ("CODIGO_MENU_USUARIO")
	  REFERENCES "SIGAMM"."SIS_MENU_USUARIO" ("CODIGO_MENU_USUARIO") ENABLE;
  ALTER TABLE "SIGAMM"."SIS_MENU_USUARIO" ADD CONSTRAINT "SIS_MENU_USUARIO_FK2" FOREIGN KEY ("CODIGO_NIVELES")
	  REFERENCES "SIGAMM"."SIS_MENU_NIVELES" ("CODIGO_NIVELES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIS_PUESTO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_PUESTO" ADD CONSTRAINT "SIS_PUESTO_FK1" FOREIGN KEY ("CODIGO_USUARIO")
	  REFERENCES "SIGAMM"."SIS_USUARIO" ("CODIGO_USUARIO") ENABLE;
  ALTER TABLE "SIGAMM"."SIS_PUESTO" ADD CONSTRAINT "SIS_PUESTO_FK2" FOREIGN KEY ("CODIGO_GIRO")
	  REFERENCES "SIGAMM"."SIS_GIRO_COMERCIAL" ("CODIGO_GIRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIS_ROL_X_UNIDAD
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" ADD CONSTRAINT "SIS_ROL_X_UNIDAD_FK1" FOREIGN KEY ("CODIGO_UNIDAD")
	  REFERENCES "SIGAMM"."SIS_UNIDAD" ("CODIGO_UNIDAD") ENABLE;
  ALTER TABLE "SIGAMM"."SIS_ROL_X_UNIDAD" ADD CONSTRAINT "SIS_ROL_X_UNIDAD_FK2" FOREIGN KEY ("CODIGO_ROL")
	  REFERENCES "SIGAMM"."SIS_ROL" ("CODIGO_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIS_USUARIO
--------------------------------------------------------

  ALTER TABLE "SIGAMM"."SIS_USUARIO" ADD CONSTRAINT "SIS_USUARIO_FK1" FOREIGN KEY ("CODIGO_ROL_X_UNIDAD")
	  REFERENCES "SIGAMM"."SIS_ROL_X_UNIDAD" ("CODIGO_ROL_X_UNIDAD") ENABLE;

--------------------------------------------------------
--  DDL for Package PKG_AUTENTICACION
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SIGAMM"."PKG_AUTENTICACION" AS 

  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_AUTENTICACION_USUARIO(vi_usuario     IN  VARCHAR2,
                             vi_clave               IN  VARCHAR2,
                             vi_ip_address          IN  VARCHAR2,
                             vo_codigo_usuario      OUT  NUMBER,
                             vo_codigo_rol          OUT  NUMBER,
                             vo_codigo_institucion  OUT  NUMBER,
                             vo_descripcion_rol     OUT  VARCHAR2,
                             vo_nombres_full        OUT  VARCHAR2,
                             vo_nombre_institucion  OUT  VARCHAR2,
                             vo_codigo_ut           OUT  NUMBER,
                             vo_nombre_ut           OUT  VARCHAR2,
                             vo_codigo              OUT  VARCHAR2,
                             vo_mensaje             OUT  VARCHAR2);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTA_OPCIONES_MENU(vi_codigo_usuario  IN  NUMBER,
                                   vo_result          OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --                                 
  
END PKG_AUTENTICACION;

/
--------------------------------------------------------
--  DDL for Package PKG_PUESTO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SIGAMM"."PKG_PUESTO" AS 
  
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTAR_GIRO_COMERCIAL(vo_result     OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_GRABAR_PUESTO(vi_codigo_puesto            IN NUMBER,
                             vi_codigo_usuario           IN NUMBER,
                             vi_codigo_giro              IN NUMBER,
                             vi_nro_puesto               IN VARCHAR,
                             vi_codigo_usuario_registro  IN NUMBER,
                             vo_codigo_puesto            OUT NUMBER,
                             vo_indicador                OUT VARCHAR,
                             vo_mensaje                  OUT VARCHAR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_REPORTE_PUESTO(vi_pagina                 IN  NUMBER,
                              vi_registros              IN  NUMBER,
                              vi_dni                    IN  VARCHAR,
                              vo_total_registros        OUT NUMBER,
                              vo_result                 OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_ELIMINAR_PUESTO(vi_codigo_puesto             IN NUMBER,
                               vi_codigo_usuario            IN NUMBER,
                               vo_indicador                 OUT VARCHAR,
                               vo_mensaje                   OUT VARCHAR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  
END PKG_PUESTO;

/
--------------------------------------------------------
--  DDL for Package PKG_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SIGAMM"."PKG_USUARIOS" AS 

  PROCEDURE SP_LISTA_ROL(vi_codigo_institucion            IN NUMBER,
                         vi_codigo_unidad                 IN NUMBER,
                         vo_result                        OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTA_UNIDAD(vi_codigo_institucion             IN NUMBER,
                            vo_result                         OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_GRABAR_USUARIO(vi_codigo_usuario         IN NUMBER,
                              vi_userid                 IN VARCHAR,
                              vi_ape_paterno            IN VARCHAR,
                              vi_ape_materno            IN VARCHAR,
                              vi_nombres                IN VARCHAR,
                              vi_fecha_nacimiento       IN VARCHAR,
                              vi_correo                 IN VARCHAR,
                              vi_telefono               IN VARCHAR,
                              vi_codigo_rol             IN NUMBER,
                              vi_codigo_unidad          IN NUMBER,
                              vi_codigo_institucion     IN NUMBER,
                              vi_estado                 IN VARCHAR,
                              vi_usuario_registro       IN VARCHAR,
                              vi_clave                  IN VARCHAR,
                              vi_dni                    IN VARCHAR,
                              vo_codigo_usuario         OUT NUMBER,
                              vo_indicador              OUT VARCHAR,
                              vo_mensaje                OUT VARCHAR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_CANTIDAD_USUARIOS(vi_codigo_institucion      IN  NUMBER,
                                 vo_cantidad                OUT  NUMBER);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_REPORTE_USUARIOS(vi_codigo_institucion     IN  NUMBER,
                                vi_pagina                 IN  NUMBER,
                                vi_registros              IN  NUMBER,
                                vi_codigo_unidad          IN  NUMBER,
                                vo_result                 OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --                                
  PROCEDURE SP_BUSCAR_USUARIO(vi_dni        IN  NUMBER,
                              vo_result     OUT SYS_REFCURSOR);
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --                                
  
END PKG_USUARIOS;

/
--------------------------------------------------------
--  DDL for Package Body PKG_AUTENTICACION
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SIGAMM"."PKG_AUTENTICACION" AS

  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_AUTENTICACION_USUARIO(vi_usuario     IN  VARCHAR2,
                             vi_clave               IN  VARCHAR2,
                             vi_ip_address          IN  VARCHAR2,
                             vo_codigo_usuario      OUT  NUMBER,
                             vo_codigo_rol          OUT  NUMBER,
                             vo_codigo_institucion  OUT  NUMBER,
                             vo_descripcion_rol     OUT  VARCHAR2,
                             vo_nombres_full        OUT  VARCHAR2,
                             vo_nombre_institucion  OUT  VARCHAR2,
                             vo_codigo_ut           OUT  NUMBER,
                             vo_nombre_ut           OUT  VARCHAR2,
                             vo_codigo              OUT  VARCHAR2,
                             vo_mensaje             OUT  VARCHAR2) AS
  BEGIN
    
    SELECT u.codigo_usuario, ru.codigo_rol, r.nombre_rol, u.apellido_paterno || ' ' || u.apellido_materno || ', ' || u.nombres AS nombres_full, ru.codigo_unidad, ut.nombre_unidad, 1, 'ACMMH'
    INTO vo_codigo_usuario, vo_codigo_rol, vo_descripcion_rol, vo_nombres_full, vo_codigo_ut, vo_nombre_ut, vo_codigo_institucion, vo_nombre_institucion
    FROM sis_usuario u
    LEFT JOIN sis_rol_x_unidad ru ON u.codigo_rol_x_unidad = ru.codigo_rol_x_unidad
    LEFT JOIN sis_rol r ON ru.codigo_rol=r.codigo_rol
    LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad
    WHERE u.estado=1
    AND ut.estado=1
    AND u.usuario=vi_usuario
    AND u.clave=vi_clave;

    vo_codigo := '00';
    vo_mensaje := 'OK';
    
  EXCEPTION 
    WHEN NO_DATA_FOUND THEN
      
        vo_codigo := '01';
        vo_mensaje := 'USUARIO O CLAVE INCORRECTA';
        vo_codigo_rol := 0;
        vo_codigo_usuario := 0;
        vo_codigo_institucion := 0;
        vo_descripcion_rol := ' ';
        vo_nombres_full := ' ';
        vo_nombre_institucion := ' ';
        vo_codigo_ut := 0;
        vo_nombre_ut := ' ';
        
  END SP_AUTENTICACION_USUARIO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTA_OPCIONES_MENU(vi_codigo_usuario  IN  NUMBER,
                                   vo_result          OUT SYS_REFCURSOR) AS
  BEGIN
      
      OPEN vo_result FOR
          SELECT m.codigo_menu, mn.codigo_niveles, m.descripcion AS desc_menu, m.orden AS orden_menu, mn.descripcion AS desc_sub_menu, mn.link, mn.orden AS orden_sub_menu, mn.nivel
          FROM sis_usuario u
          LEFT JOIN sis_menu_usuario mu ON u.codigo_usuario=mu.codigo_usuario
          LEFT JOIN sis_menu_niveles mn ON mu.codigo_niveles=mn.codigo_niveles
          LEFT JOIN sis_menu m ON mn.codigo_menu=m.codigo_menu
          WHERE u.estado = 1
          AND m.estado = 1
          AND mn.estado = 1
          AND u.codigo_usuario = vi_codigo_usuario
          ORDER BY m.orden, mn.orden;
          
  END SP_LISTA_OPCIONES_MENU;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  
END PKG_AUTENTICACION;

/
--------------------------------------------------------
--  DDL for Package Body PKG_PUESTO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SIGAMM"."PKG_PUESTO" AS
  
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTAR_GIRO_COMERCIAL(vo_result     OUT SYS_REFCURSOR) AS
  BEGIN
      
      OPEN vo_result FOR
          SELECT codigo_giro, nombre_giro FROM sis_giro_comercial
          WHERE estado = 1
          ORDER BY nombre_giro;
          
  END SP_LISTAR_GIRO_COMERCIAL;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_GRABAR_PUESTO(vi_codigo_puesto            IN NUMBER,
                             vi_codigo_usuario           IN NUMBER,
                             vi_codigo_giro              IN NUMBER,
                             vi_nro_puesto               IN VARCHAR,
                             vi_codigo_usuario_registro  IN NUMBER,
                             vo_codigo_puesto            OUT NUMBER,
                             vo_indicador                OUT VARCHAR,
                             vo_mensaje                  OUT VARCHAR) AS
  
  vl_codigo                 NUMBER;                              
  BEGIN
    
    IF vi_codigo_puesto = 0 THEN
        
        SELECT SEQ_SIS_CODIGO_PUESTO.NEXTVAL INTO vl_codigo FROM DUAL;
        INSERT INTO sis_puesto (codigo_puesto, codigo_usuario, nro_puesto, codigo_giro, usuario_registro, fecha_registro, estado)
        VALUES (vl_codigo, vi_codigo_usuario, vi_nro_puesto, vi_codigo_giro, vi_codigo_usuario_registro, SYSDATE, 1);
        
        vo_codigo_puesto := vl_codigo;
        vo_indicador := '00';
        vo_mensaje := 'Se registro satisfactoriamente el puesto.';
    ELSE
    
        UPDATE sis_puesto
        SET
        nro_puesto = vi_nro_puesto, 
        codigo_giro = vi_codigo_giro,
        usuario_modificacion = vi_codigo_usuario_registro, 
        fecha_modificacion = SYSDATE
        WHERE codigo_usuario = vi_codigo_usuario
        AND codigo_puesto = vi_codigo_puesto;
        
        vo_codigo_puesto := vi_codigo_puesto;
        vo_indicador := '00';
        vo_mensaje := 'Se modifico satisfactoriamente el puesto.';
        
    END IF;
  
  EXCEPTION 
    WHEN OTHERS THEN
      vo_codigo_puesto := 0;
      vo_indicador := '01';
      vo_mensaje := SQLCODE || ' - ' || SQLERRM;
      ROLLBACK;  
    
  END SP_GRABAR_PUESTO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_REPORTE_PUESTO(vi_pagina                 IN  NUMBER,
                              vi_registros              IN  NUMBER,
                              vi_dni                    IN  VARCHAR,
                              vo_total_registros        OUT NUMBER,
                              vo_result                 OUT SYS_REFCURSOR) AS
  vl_inicio NUMBER;
  vl_fin    NUMBER;                              
  BEGIN
    
    vl_fin := vi_pagina * vi_registros;
    vl_inicio := vl_fin - (vi_registros - 1);
    
    dbms_output.put_line ('INICIO : ' || vl_inicio); 
    dbms_output.put_line ('FIN : ' || vl_fin); 
    
    IF vi_dni = '0' THEN
    
        SELECT COUNT(*) INTO vo_total_registros
        FROM sis_puesto p
        LEFT JOIN sis_usuario u ON p.codigo_usuario = u.codigo_usuario
        LEFT JOIN sis_giro_comercial g ON p.codigo_giro = g.codigo_giro;
        
        OPEN vo_result FOR
            SELECT codigo_puesto, codigo_usuario, nro_puesto, codigo_giro, dni, nombre_full, nombre_giro
            FROM (
                SELECT codigo_puesto, codigo_usuario, nro_puesto, codigo_giro, dni, nombre_full, nombre_giro, ROWNUM numfila
                FROM (
                
                      SELECT p.codigo_puesto, p.codigo_usuario, p.nro_puesto, p.codigo_giro, u.dni, u.apellido_paterno || ' ' || u.apellido_materno || ', ' || u.nombres AS nombre_full, g.nombre_giro
                      FROM sis_puesto p
                      LEFT JOIN sis_usuario u ON p.codigo_usuario = u.codigo_usuario
                      LEFT JOIN sis_giro_comercial g ON p.codigo_giro = g.codigo_giro
    
                ) A
            ) B
            WHERE numfila BETWEEN vl_inicio AND vl_fin;
            
    ELSE
    
        SELECT COUNT(*) INTO vo_total_registros
        FROM sis_puesto p
        LEFT JOIN sis_usuario u ON p.codigo_usuario = u.codigo_usuario
        LEFT JOIN sis_giro_comercial g ON p.codigo_giro = g.codigo_giro
        WHERE u.dni = vi_dni;
        
        OPEN vo_result FOR
            SELECT codigo_puesto, codigo_usuario, nro_puesto, codigo_giro, dni, nombre_full, nombre_giro
            FROM (
                SELECT codigo_puesto, codigo_usuario, nro_puesto, codigo_giro, dni, nombre_full, nombre_giro, ROWNUM numfila
                FROM (
                
                      SELECT p.codigo_puesto, p.codigo_usuario, p.nro_puesto, p.codigo_giro, u.dni, u.apellido_paterno || ' ' || u.apellido_materno || ', ' || u.nombres AS nombre_full, g.nombre_giro
                      FROM sis_puesto p
                      LEFT JOIN sis_usuario u ON p.codigo_usuario = u.codigo_usuario
                      LEFT JOIN sis_giro_comercial g ON p.codigo_giro = g.codigo_giro
                      WHERE u.dni = vi_dni
                      
                ) A
            ) B
            WHERE numfila BETWEEN vl_inicio AND vl_fin;
        
    END IF;
  END SP_REPORTE_PUESTO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_ELIMINAR_PUESTO(vi_codigo_puesto            IN NUMBER,
                               vi_codigo_usuario           IN NUMBER,
                               vo_indicador                OUT VARCHAR,
                               vo_mensaje                  OUT VARCHAR) AS
  BEGIN
    
    UPDATE sis_puesto
    SET
    estado = 0, 
    usuario_modificacion = vi_codigo_usuario, 
    fecha_modificacion = SYSDATE
    WHERE codigo_puesto = vi_codigo_puesto;
        
    vo_indicador := '00';
    vo_mensaje := 'Se elimino el puesto.';
  
  EXCEPTION 
    WHEN OTHERS THEN
      vo_indicador := '01';
      vo_mensaje := SQLCODE || ' - ' || SQLERRM;
      ROLLBACK;  
      
  END SP_ELIMINAR_PUESTO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  
END PKG_PUESTO;

/
--------------------------------------------------------
--  DDL for Package Body PKG_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "SIGAMM"."PKG_USUARIOS" AS

  PROCEDURE SP_LISTA_ROL(vi_codigo_institucion            IN NUMBER,
                         vi_codigo_unidad                 IN NUMBER,
                         vo_result                        OUT SYS_REFCURSOR) AS
  BEGIN
    
    OPEN vo_result FOR
        SELECT r.codigo_rol, r.nombre_rol from sis_rol_x_unidad ru
        LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad
        LEFT JOIN sis_rol r ON ru.codigo_rol=r.codigo_rol
        WHERE ut.estado=1
        AND r.estado=1
        AND ru.codigo_unidad=vi_codigo_unidad
        ORDER BY r.codigo_rol;

  END SP_LISTA_ROL;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_LISTA_UNIDAD(vi_codigo_institucion             IN NUMBER,
                            vo_result                         OUT SYS_REFCURSOR) AS
  BEGIN
    
    OPEN vo_result FOR
        SELECT codigo_unidad, nombre_unidad FROM sis_unidad
        WHERE estado = 1
        ORDER BY nombre_unidad;
        
  END SP_LISTA_UNIDAD;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_GRABAR_USUARIO(vi_codigo_usuario         IN NUMBER,
                              vi_userid                 IN VARCHAR,
                              vi_ape_paterno            IN VARCHAR,
                              vi_ape_materno            IN VARCHAR,
                              vi_nombres                IN VARCHAR,
                              vi_fecha_nacimiento       IN VARCHAR,
                              vi_correo                 IN VARCHAR,
                              vi_telefono               IN VARCHAR,
                              vi_codigo_rol             IN NUMBER,
                              vi_codigo_unidad          IN NUMBER,
                              vi_codigo_institucion     IN NUMBER,
                              vi_estado                 IN VARCHAR,
                              vi_usuario_registro       IN VARCHAR,
                              vi_clave                  IN VARCHAR,
                              vi_dni                    IN VARCHAR,
                              vo_codigo_usuario         OUT NUMBER,
                              vo_indicador              OUT VARCHAR,
                              vo_mensaje                OUT VARCHAR) AS
  vl_codigo                 NUMBER;
  vl_estado                 NUMBER;
  vl_codigo_menu_usuario    NUMBER;
  vl_codigo_rol_x_unidad    NUMBER;
  BEGIN
    
    IF vi_estado = 'ACTIVO' THEN
      vl_estado := 1;
    ELSE
      vl_estado := 0;
    END IF;
    
    SELECT ru.codigo_rol_x_unidad INTO vl_codigo_rol_x_unidad
    FROM sis_rol_x_unidad ru
    LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad
    WHERE ut.estado=1
    AND ru.codigo_unidad=vi_codigo_unidad
    AND ru.codigo_rol=vi_codigo_rol;
    
    IF vi_codigo_usuario = 0 THEN
        
        SELECT SEQ_SIS_CODIGO_USUARIO.NEXTVAL INTO vl_codigo FROM DUAL;
        INSERT INTO sis_usuario (codigo_usuario, usuario, clave, apellido_paterno, apellido_materno, nombres, fecha_nacimiento, correo, estado, usuario_creacion, fecha_creacion, codigo_rol_x_unidad, telefono, dni)
        VALUES (vl_codigo, vi_userid, vi_clave, vi_ape_paterno, vi_ape_materno, vi_nombres, vi_fecha_nacimiento, vi_correo, vl_estado, vi_usuario_registro, SYSDATE, vl_codigo_rol_x_unidad, vi_telefono, vi_dni);
        /*
        SELECT SEQ_SIS_MENU_USUARIO.NEXTVAL INTO vl_codigo_menu_usuario FROM DUAL;
        INSERT INTO sis_menu_usuario (codigo_menu_usuario, codigo_niveles, codigo_usuario)
        VALUES(vl_codigo_menu_usuario, 1, vl_codigo);
        */
        /* 
        UPDATE AY_VERSION
        SET versionoperadores = vl_operador + 1;
        */
        vo_codigo_usuario := vl_codigo;
        vo_indicador := '00';
        vo_mensaje := 'OK';
    ELSE
    
        UPDATE sis_usuario
        SET
        apellido_paterno = vi_ape_paterno, 
        apellido_materno = vi_ape_materno, 
        nombres = vi_nombres, 
        fecha_nacimiento = vi_fecha_nacimiento, 
        correo = vi_correo, 
        telefono = vi_telefono, 
        dni = vi_dni,
        estado = vl_estado, 
        usuario_modificacion = vi_usuario_registro, 
        fecha_creacion = SYSDATE,
        codigo_rol_x_unidad=vl_codigo_rol_x_unidad
        WHERE 
        codigo_usuario = vi_codigo_usuario;
        
        /*
        UPDATE AY_VERSION
        SET versionoperadores = vl_operador + 1;
        */
        vo_codigo_usuario := vi_codigo_usuario;
        vo_indicador := '00';
        vo_mensaje := 'OK';
    END IF;
  
  EXCEPTION 
    WHEN OTHERS THEN
      vo_codigo_usuario := 0;
      vo_indicador := '01';
      vo_mensaje := SQLCODE || ' - ' || SQLERRM;
      ROLLBACK;  
      
  END SP_GRABAR_USUARIO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_CANTIDAD_USUARIOS(vi_codigo_institucion      IN  NUMBER,
                                 vo_cantidad                OUT  NUMBER) AS
  BEGIN
    
    SELECT COUNT(*) INTO vo_cantidad
        FROM sis_usuario u
        LEFT JOIN sis_rol_x_unidad ru ON u.codigo_rol_x_unidad = ru.codigo_rol_x_unidad
        LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad;
        
  END SP_CANTIDAD_USUARIOS;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_REPORTE_USUARIOS(vi_codigo_institucion     IN  NUMBER,
                                vi_pagina                 IN  NUMBER,
                                vi_registros              IN  NUMBER,
                                vi_codigo_unidad          IN  NUMBER,
                                vo_result                 OUT SYS_REFCURSOR) AS
  vl_inicio NUMBER;
  vl_fin    NUMBER;                              
  BEGIN
    
    vl_fin := vi_pagina * vi_registros;
    vl_inicio := vl_fin - (vi_registros - 1);
    
    dbms_output.put_line ('INICIO : ' || vl_inicio); 
    dbms_output.put_line ('FIN : ' || vl_fin); 
    
    OPEN vo_result FOR
        SELECT codigo_usuario, usuario as userid, NVL(apellido_paterno, ' ') AS apellido_paterno, NVL(apellido_materno, ' ') AS apellido_materno, NVL(nombres, ' ') AS nombres, TO_CHAR(fecha_nacimiento, 'DD/MM/YYYY') AS fecha_nacimiento, 
        correo, codigo_rol, nombre_rol, codigo_unidad, nombre_unidad, 
        codigo_institucion, CASE WHEN estado = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS estado, dni, telefono
        FROM (
            SELECT codigo_usuario, usuario, apellido_paterno, apellido_materno, nombres, fecha_nacimiento, correo, codigo_rol, nombre_rol, codigo_unidad, nombre_unidad,
            codigo_institucion, estado, dni, telefono, ROWNUM numfila
            FROM (
                  SELECT u.codigo_usuario, u.usuario, u.apellido_paterno, u.apellido_materno, u.nombres, u.fecha_nacimiento, u.correo, ru.codigo_rol, r.nombre_rol, ru.codigo_unidad, ut.nombre_unidad, 
                  1 AS codigo_institucion, u.estado, u.dni, u.telefono
                  FROM sis_usuario u
                  LEFT JOIN sis_rol_x_unidad ru ON u.codigo_rol_x_unidad=ru.codigo_rol_x_unidad
                  LEFT JOIN sis_rol r ON ru.codigo_rol=r.codigo_rol
                  LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad
                  WHERE ut.codigo_unidad = vi_codigo_unidad
                  ORDER BY u.usuario
            ) A
        ) B
        WHERE numfila BETWEEN vl_inicio AND vl_fin;

  END SP_REPORTE_USUARIOS;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  PROCEDURE SP_BUSCAR_USUARIO(vi_dni        IN  NUMBER,
                              vo_result     OUT SYS_REFCURSOR) AS
  BEGIN
      
      OPEN vo_result FOR
          SELECT u.codigo_usuario, u.usuario as userid, u.apellido_paterno, u.apellido_materno, u.nombres, u.fecha_nacimiento, u.correo, ru.codigo_rol, r.nombre_rol, ru.codigo_unidad, ut.nombre_unidad, 
          1 AS codigo_institucion, u.estado, u.dni, u.telefono
          FROM sis_usuario u
          LEFT JOIN sis_rol_x_unidad ru ON u.codigo_rol_x_unidad=ru.codigo_rol_x_unidad
          LEFT JOIN sis_rol r ON ru.codigo_rol=r.codigo_rol
          LEFT JOIN sis_unidad ut ON ru.codigo_unidad=ut.codigo_unidad
          WHERE u.dni = vi_dni
          ORDER BY u.usuario;
      
  END SP_BUSCAR_USUARIO;
  -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  
END PKG_USUARIOS;

/
